### ISSUE TITLE
Visualizing the last lap

### ISSUE THREAD

**Issue by franzmoro** [vanillasquad/stopwatch-katherine-andrew#29]
...requires scrolling after the 6th / 7th lap on the desktop version. I liked everything else! Congrats!!

**Comment by andrewMacmurray** [comment]
@franzmoro thanks, will have a think about how to implement this

**Comment by andrewMacmurray** [comment]
@franzmoro we've had a look at this and we think a scrolling page fits our design better than a scroll box (either as a box with borders or just a floating scroll bar)

**Comment by franzmoro** [comment]
ok. scroll box isn't necessarily the way to do it. i'll close the issue anyway, the stopwatch is great.
